config/routes.rb
Rails.application.routes.draw do
  resources :service_attribute_values
  resources :service_attributes
  resources :service_definitions
  resources :jurisdictions
  resources :services

end

app/models/service.rb
class Service < ActiveRecord::Base

  enum service_type: [ :realtime, :batch, :blackbox ]

  belongs_to :jurisdiction
  has_one :service_definition, dependent: :destroy

  validates_presence_of :jurisdiction_id, :service_type
  validates_associated :service_definition

  after_create :add_service_definition

  private

  def add_service_definition
    create_service_definition(service_id: id, service_code: service_code)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  def index
    @services = Service.all
  end

  # GET /services/1
  def show
    begin
      Jurisdiction.find(@service.jurisdiction_id)
    rescue ActiveRecord::RecordNotFound
      render status: :not_found
    end
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to @service, notice: 'Service was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /services/1
  def update
    if @service.update(service_params)
      redirect_to @service, notice: 'Service was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /services/1
  def destroy
    @service.destroy
    redirect_to services_url, notice: 'Service was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def service_params
      params.require(:service).permit(:service_code, :service_name, :service_type, :description, :metadata, :keywords, :group, :jurisdiction_id)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

  <table>
  <tr>
    <th><%= f.label :service_code %></th>
    <td><%= f.text_field :service_code %></td>
    <td>The unique identifier for the service request type</td>
  </tr>
  <tr>
    <th><%= f.label :service_name %></th>
    <td><%= f.text_field :service_name %></td>
    <td>The human readable name of the service request type</td>
  </tr>
  <tr>
    <th><%= f.label :description %></th>
    <td><%= f.text_area :description %></td>
    <td>A brief description of the service request type.	</td>
  </tr>
  <tr>
    <th><%= f.label :metadata %></th>
    <td><%= f.check_box :metadata %></td>
    <td>Determines whether there are additional form fields for this service type.
      <dl>
        <dt>true</dt>
        <dd>This service request type requires additional metadata so the client will need to make a call to the Service Definition method.</dd>
        <dt>false</dt>
        <dd>No additional information is required and a call to the Service Definition method is not needed.</dd>
      </dl>
    </td>
  </tr>
  <tr>
    <th><%= f.label :service_type %></th>
    <td><%= f.text_field :service_type %></td>
    <td>
      <dl>
        <dt>realtime</dt>
        <dd>The service request ID will be returned immediately after the service request is submitted.</dd>
        <dt>batch</dt>
        <dd>A token will be returned immediately after the service request is submitted. This token can then be later used to return the service request ID.</dd>
        <dt>blackbox</dt>
        <dd>No service request ID will be returned after the service request is submitted.</dd>
      </dl>
    </td>
  </tr>
  <tr>
    <th><%= f.label :keywords %></th>
    <td><%= f.text_area :keywords %></td>
    <td>A comma separated list of tags or keywords to help users identify the request type. This can provide synonyms of the service_name and group.</td>
  </tr>
  <tr>
    <th><%= f.label :group %></th>
    <td><%= f.text_field :group %></td>
    <td>A category to group this service type within. This provides a way to group several service request types under one category such as “sanitation”</td>
  </tr>
  <tr>
    <th><%= f.label :jurisdiction_id %></th>
    <td><%= f.select :jurisdiction_id, Jurisdiction.all.collect { |p| [ p.name, p.id ] }, prompt: true %>
    </td>
    <td></td>
    <td><span class='alert'>This is only required if the endpoint serves multiple jurisdictions</span></td>
  </tr>
</table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Services</h1>

<table>
  <thead>
    <tr>
      <th>Service code</th>
      <th>Service name</th>
      <th>Description</th>
      <th>Metadata</th>
      <th>Service type</th>
      <th>Keywords</th>
      <th>Group</th>
      <th>Jurisdiction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= link_to service.service_code, service %></td>
        <td><%= service.service_name %></td>
        <td><%= service.description %></td>
        <td><%= service.metadata %></td>
        <td><%= service.service_type %></td>
        <td><%= service.keywords %></td>
        <td><%= service.group %></td>
        <td><%= service.jurisdiction.name %></td>

        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>Add a Service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>
<div style="color: red;"><%= @service.service_definition.inspect %></div>
<p>
  <strong>Service code:</strong>
  <%= @service.service_code %>
</p>

<p>
  <strong>Service name:</strong>
  <%= @service.service_name %>
</p>

<p>
  <strong>Service type:</strong>
  <%= @service.service_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Metadata:</strong>
  <%= @service.metadata %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @service.keywords %>
</p>

<p>
  <strong>Group:</strong>
  <%= @service.group %>
</p>

<p>
  <strong>Jurisdiction:</strong>
  <%= @service.jurisdiction_id %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>