config/routes.rb
Rails.application.routes.draw do
  resources :service_attribute_values
  resources :service_attributes
  resources :service_definitions
  resources :jurisdictions
  resources :services

end

app/models/service_definition.rb
class ServiceDefinition < ActiveRecord::Base

  belongs_to :service
  has_many :service_attributes

  validates_presence_of :service_id, :service_code
end

app/controllers/service_definitions_controller.rb
class ServiceDefinitionsController < ApplicationController
  before_action :set_service_definition, only: [:show, :edit, :update, :destroy]

  # GET /service_definitions
  def index
    @service_definitions = ServiceDefinition.all
  end

  # GET /service_definitions/1
  def show
  end

  # GET /service_definitions/new
  def new
    @service_definition = ServiceDefinition.new
  end

  # GET /service_definitions/1/edit
  def edit
  end

  # POST /service_definitions
  def create
    @service_definition = ServiceDefinition.new(service_definition_params)
    if @service_definition.save
      redirect_to @service_definition, notice: 'Service definition was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /service_definitions/1
  def update
    if @service_definition.update(service_definition_params)
      redirect_to @service_definition, notice: 'Service definition was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /service_definitions/1
  def destroy
    @service_definition.destroy
    redirect_to service_definitions_url, notice: 'Service definition was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_definition
      @service_definition = ServiceDefinition.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def service_definition_params
      # [ params[:service_id], params[:service_code] ]
      fail "#{params.inspect}"
    end
end

app/helpers/service_definitions_helper.rb
module ServiceDefinitionsHelper
end

app/views/service_definitions/_form.html.erb
<%= form_for(@service_definition) do |f| %>
  <% if @service_definition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_definition.errors.count, "error") %> prohibited this service_definition from being saved:</h2>

      <ul>
      <% @service_definition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <th><%= f.label :service_id %></th>
      <td><%= f.number_field :service_id %></td>
    </tr>
    <tr>
      <th><%= f.label :service_code %></th>
      <td><%= f.text_field :service_code %></td>
    </tr>
    <tr>
      <td></td>
      <td class="actions"><%= f.submit %></td>
    </tr>
  </table>
<% end %>

app/views/service_definitions/edit.html.erb
<h1>Editing Service Definition</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_definition %> |
<%= link_to 'Back', service_definitions_path %>

app/views/service_definitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Service Definitions</h1>

<table>
  <thead>
    <tr>
      <th>Service</th>
      <th>Service code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_definitions.each do |service_definition| %>
      <tr>
        <td><%= service_definition.service_id %></td>
        <td><%= service_definition.service_code %></td>
        <td><%= link_to 'Show', service_definition %></td>
        <td><%= link_to 'Edit', edit_service_definition_path(service_definition) %></td>
        <td><%= link_to 'Destroy', service_definition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service definition', new_service_definition_path %>

app/views/service_definitions/new.html.erb
<h1>New Service Definition</h1>

<%= render 'form' %>

<%= link_to 'Back', service_definitions_path %>

app/views/service_definitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service:</strong>
  <%= @service_definition.service_id %>
</p>

<p>
  <strong>Service code:</strong>
  <%= @service_definition.service_code %>
</p>

<%= link_to 'Edit', edit_service_definition_path(@service_definition) %> |
<%= link_to 'Back', service_definitions_path %>