config/routes.rb
Rails.application.routes.draw do
  resources :service_attribute_values
  resources :service_attributes
  resources :service_definitions
  resources :jurisdictions
  resources :services

end

app/models/jurisdiction.rb
class Jurisdiction < ActiveRecord::Base

  has_many :services

  validates_presence_of :name

end

app/controllers/jurisdictions_controller.rb
class JurisdictionsController < ApplicationController
  before_action :set_jurisdiction, only: [:show, :edit, :update, :destroy]

  # GET /jurisdictions
  def index
    @jurisdictions = Jurisdiction.all
  end

  # GET /jurisdictions/1
  def show
  end

  # GET /jurisdictions/new
  def new
    @jurisdiction = Jurisdiction.new
  end

  # GET /jurisdictions/1/edit
  def edit
  end

  # POST /jurisdictions
  def create
    @jurisdiction = Jurisdiction.new(jurisdiction_params)

    if @jurisdiction.save
      redirect_to @jurisdiction, notice: 'Jurisdiction was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /jurisdictions/1
  def update
    if @jurisdiction.update(jurisdiction_params)
      redirect_to @jurisdiction, notice: 'Jurisdiction was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /jurisdictions/1
  def destroy
    @jurisdiction.destroy
    redirect_to jurisdictions_url, notice: 'Jurisdiction was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jurisdiction
      @jurisdiction = Jurisdiction.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def jurisdiction_params
      params.require(:jurisdiction).permit(:name)
    end
end

app/helpers/jurisdictions_helper.rb
module JurisdictionsHelper
end

app/views/jurisdictions/_form.html.erb
<%= form_for(@jurisdiction) do |f| %>
  <% if @jurisdiction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jurisdiction.errors.count, "error") %> prohibited this jurisdiction from being saved:</h2>

      <ul>
      <% @jurisdiction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jurisdictions/edit.html.erb
<h1>Editing Jurisdiction</h1>

<%= render 'form' %>

<%= link_to 'Show', @jurisdiction %> |
<%= link_to 'Back', jurisdictions_path %>

app/views/jurisdictions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jurisdictions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jurisdictions.each do |jurisdiction| %>
      <tr>
        <td><%= jurisdiction.name %></td>
        <td><%= link_to 'Show', jurisdiction %></td>
        <td><%= link_to 'Edit', edit_jurisdiction_path(jurisdiction) %></td>
        <td><%= link_to 'Destroy', jurisdiction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jurisdiction', new_jurisdiction_path %>

app/views/jurisdictions/new.html.erb
<h1>New Jurisdiction</h1>

<%= render 'form' %>

<%= link_to 'Back', jurisdictions_path %>

app/views/jurisdictions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @jurisdiction.name %>
</p>

<%= link_to 'Edit', edit_jurisdiction_path(@jurisdiction) %> |
<%= link_to 'Back', jurisdictions_path %>