config/routes.rb
Rails.application.routes.draw do
  resources :service_attribute_values
  resources :service_attributes
  resources :service_definitions
  resources :jurisdictions
  resources :services

end

app/models/service_attribute_value.rb
class ServiceAttributeValue < ActiveRecord::Base

  belongs_to :service_attribute

  validates_presence_of :service_attribute_id, :key, :name
end

app/controllers/service_attribute_values_controller.rb
class ServiceAttributeValuesController < ApplicationController
  before_action :set_service_attribute_value, only: [:show, :edit, :update, :destroy]

  # GET /service_attribute_values
  def index
    @service_attribute_values = ServiceAttributeValue.all
  end

  # GET /service_attribute_values/1
  def show
  end

  # GET /service_attribute_values/new
  def new
    @service_attribute_value = ServiceAttributeValue.new
  end

  # GET /service_attribute_values/1/edit
  def edit
  end

  # POST /service_attribute_values
  def create
    @service_attribute_value = ServiceAttributeValue.new(service_attribute_value_params)

    if @service_attribute_value.save
      redirect_to @service_attribute_value, notice: 'Service attribute value was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /service_attribute_values/1
  def update
    if @service_attribute_value.update(service_attribute_value_params)
      redirect_to @service_attribute_value, notice: 'Service attribute value was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /service_attribute_values/1
  def destroy
    @service_attribute_value.destroy
    redirect_to service_attribute_values_url, notice: 'Service attribute value was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_attribute_value
      @service_attribute_value = ServiceAttributeValue.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def service_attribute_value_params
      params.require(:service_attribute_value).permit(:service_attribute_id, :key, :name)
    end
end

app/helpers/service_attribute_values_helper.rb
module ServiceAttributeValuesHelper
end

app/views/service_attribute_values/_form.html.erb
<%= form_for(@service_attribute_value) do |f| %>
  <% if @service_attribute_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_attribute_value.errors.count, "error") %> prohibited this service_attribute_value from being saved:</h2>

      <ul>
      <% @service_attribute_value.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :service_attribute_id %><br>
    <%= f.number_field :service_attribute_id %>
  </div>
  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/service_attribute_values/edit.html.erb
<h1>Editing Service Attribute Value</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_attribute_value %> |
<%= link_to 'Back', service_attribute_values_path %>

app/views/service_attribute_values/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Service Attribute Values</h1>

<table>
  <thead>
    <tr>
      <th>Service attribute</th>
      <th>Key</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_attribute_values.each do |service_attribute_value| %>
      <tr>
        <td><%= service_attribute_value.service_attribute_id %></td>
        <td><%= service_attribute_value.key %></td>
        <td><%= service_attribute_value.name %></td>
        <td><%= link_to 'Show', service_attribute_value %></td>
        <td><%= link_to 'Edit', edit_service_attribute_value_path(service_attribute_value) %></td>
        <td><%= link_to 'Destroy', service_attribute_value, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service attribute value', new_service_attribute_value_path %>

app/views/service_attribute_values/new.html.erb
<h1>New Service Attribute Value</h1>

<%= render 'form' %>

<%= link_to 'Back', service_attribute_values_path %>

app/views/service_attribute_values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service attribute:</strong>
  <%= @service_attribute_value.service_attribute_id %>
</p>

<p>
  <strong>Key:</strong>
  <%= @service_attribute_value.key %>
</p>

<p>
  <strong>Name:</strong>
  <%= @service_attribute_value.name %>
</p>

<%= link_to 'Edit', edit_service_attribute_value_path(@service_attribute_value) %> |
<%= link_to 'Back', service_attribute_values_path %>